version: '3'
services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - $LOCAL_WORKSPACE_FOLDER/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - dev-network

  redis:
    image: redis:6
    ports:
      - 6379:6379
  # identity:
  #   build: 
  #     context: .
  #     dockerfile: ./build/docker/dockerfile
  #   ports:
  #     - 12568:12568

networks:
  dev-network:
    name: dev-network