// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/identity/proto/identity.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Account struct {
	ID                    string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	App                   string   `protobuf:"bytes,2,opt,name=App,proto3" json:"App,omitempty"`
	Username              string   `protobuf:"bytes,3,opt,name=Username,proto3" json:"Username,omitempty"`
	PasswordHash          string   `protobuf:"bytes,4,opt,name=PasswordHash,proto3" json:"PasswordHash,omitempty"`
	FirstName             string   `protobuf:"bytes,5,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName              string   `protobuf:"bytes,6,opt,name=LastName,proto3" json:"LastName,omitempty"`
	ExternalID            string   `protobuf:"bytes,7,opt,name=ExternalID,proto3" json:"ExternalID,omitempty"`
	IsLockedOut           bool     `protobuf:"varint,8,opt,name=IsLockedOut,proto3" json:"IsLockedOut,omitempty"`
	FailedPasswordAttempt int32    `protobuf:"varint,9,opt,name=FailedPasswordAttempt,proto3" json:"FailedPasswordAttempt,omitempty"`
	Roles                 []string `protobuf:"bytes,10,rep,name=Roles,proto3" json:"Roles,omitempty"`
	LastLoginAt           int32    `protobuf:"varint,11,opt,name=LastLoginAt,proto3" json:"LastLoginAt,omitempty"`
	CreatedAt             int32    `protobuf:"varint,12,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt             int32    `protobuf:"varint,13,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_489bdd7b772540d3, []int{0}
}
func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (dst *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(dst, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Account) GetApp() string {
	if m != nil {
		return m.App
	}
	return ""
}

func (m *Account) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Account) GetPasswordHash() string {
	if m != nil {
		return m.PasswordHash
	}
	return ""
}

func (m *Account) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Account) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Account) GetExternalID() string {
	if m != nil {
		return m.ExternalID
	}
	return ""
}

func (m *Account) GetIsLockedOut() bool {
	if m != nil {
		return m.IsLockedOut
	}
	return false
}

func (m *Account) GetFailedPasswordAttempt() int32 {
	if m != nil {
		return m.FailedPasswordAttempt
	}
	return 0
}

func (m *Account) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *Account) GetLastLoginAt() int32 {
	if m != nil {
		return m.LastLoginAt
	}
	return 0
}

func (m *Account) GetCreatedAt() int32 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Account) GetUpdatedAt() int32 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type AccountByTokenRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountByTokenRequest) Reset()         { *m = AccountByTokenRequest{} }
func (m *AccountByTokenRequest) String() string { return proto.CompactTextString(m) }
func (*AccountByTokenRequest) ProtoMessage()    {}
func (*AccountByTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_489bdd7b772540d3, []int{1}
}
func (m *AccountByTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountByTokenRequest.Unmarshal(m, b)
}
func (m *AccountByTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountByTokenRequest.Marshal(b, m, deterministic)
}
func (dst *AccountByTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountByTokenRequest.Merge(dst, src)
}
func (m *AccountByTokenRequest) XXX_Size() int {
	return xxx_messageInfo_AccountByTokenRequest.Size(m)
}
func (m *AccountByTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountByTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountByTokenRequest proto.InternalMessageInfo

func (m *AccountByTokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type EmptyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyRequest) Reset()         { *m = EmptyRequest{} }
func (m *EmptyRequest) String() string { return proto.CompactTextString(m) }
func (*EmptyRequest) ProtoMessage()    {}
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_489bdd7b772540d3, []int{2}
}
func (m *EmptyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyRequest.Unmarshal(m, b)
}
func (m *EmptyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyRequest.Marshal(b, m, deterministic)
}
func (dst *EmptyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyRequest.Merge(dst, src)
}
func (m *EmptyRequest) XXX_Size() int {
	return xxx_messageInfo_EmptyRequest.Size(m)
}
func (m *EmptyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyRequest proto.InternalMessageInfo

type EmptyReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyReply) Reset()         { *m = EmptyReply{} }
func (m *EmptyReply) String() string { return proto.CompactTextString(m) }
func (*EmptyReply) ProtoMessage()    {}
func (*EmptyReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_489bdd7b772540d3, []int{3}
}
func (m *EmptyReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyReply.Unmarshal(m, b)
}
func (m *EmptyReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyReply.Marshal(b, m, deterministic)
}
func (dst *EmptyReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyReply.Merge(dst, src)
}
func (m *EmptyReply) XXX_Size() int {
	return xxx_messageInfo_EmptyReply.Size(m)
}
func (m *EmptyReply) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyReply.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyReply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Account)(nil), "proto.Account")
	proto.RegisterType((*AccountByTokenRequest)(nil), "proto.AccountByTokenRequest")
	proto.RegisterType((*EmptyRequest)(nil), "proto.EmptyRequest")
	proto.RegisterType((*EmptyReply)(nil), "proto.EmptyReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// IdentityServiceClient is the client API for IdentityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IdentityServiceClient interface {
	AccountByToken(ctx context.Context, in *AccountByTokenRequest, opts ...grpc.CallOption) (*Account, error)
}

type identityServiceClient struct {
	cc *grpc.ClientConn
}

func NewIdentityServiceClient(cc *grpc.ClientConn) IdentityServiceClient {
	return &identityServiceClient{cc}
}

func (c *identityServiceClient) AccountByToken(ctx context.Context, in *AccountByTokenRequest, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := c.cc.Invoke(ctx, "/proto.IdentityService/AccountByToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityServiceServer is the server API for IdentityService service.
type IdentityServiceServer interface {
	AccountByToken(context.Context, *AccountByTokenRequest) (*Account, error)
}

func RegisterIdentityServiceServer(s *grpc.Server, srv IdentityServiceServer) {
	s.RegisterService(&_IdentityService_serviceDesc, srv)
}

func _IdentityService_AccountByToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountByTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).AccountByToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.IdentityService/AccountByToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).AccountByToken(ctx, req.(*AccountByTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _IdentityService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.IdentityService",
	HandlerType: (*IdentityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AccountByToken",
			Handler:    _IdentityService_AccountByToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/identity/proto/identity.proto",
}

func init() {
	proto.RegisterFile("pkg/identity/proto/identity.proto", fileDescriptor_identity_489bdd7b772540d3)
}

var fileDescriptor_identity_489bdd7b772540d3 = []byte{
	// 354 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xdf, 0x4e, 0x83, 0x30,
	0x14, 0xc6, 0x65, 0xc8, 0x36, 0xce, 0x10, 0x4d, 0xe3, 0x92, 0x66, 0x59, 0x0c, 0x72, 0xc5, 0x8d,
	0x5b, 0xa2, 0x3e, 0x80, 0xe8, 0xb6, 0x48, 0xb2, 0xa8, 0x61, 0xee, 0x01, 0x10, 0x9a, 0x49, 0xc6,
	0x68, 0xa5, 0x9d, 0xca, 0x63, 0xf8, 0xc6, 0xa6, 0x85, 0xfd, 0x4b, 0x76, 0x05, 0xdf, 0xef, 0xd7,
	0x7c, 0x3d, 0xe4, 0x00, 0xd7, 0x6c, 0xb9, 0x18, 0xa6, 0x09, 0xc9, 0x45, 0x2a, 0xca, 0x21, 0x2b,
	0xa8, 0xa0, 0xdb, 0x38, 0x50, 0x11, 0x19, 0xea, 0xe1, 0xfe, 0xe9, 0xd0, 0xf2, 0xe3, 0x98, 0xae,
	0x73, 0x81, 0x6c, 0x68, 0x04, 0x23, 0xac, 0x39, 0x9a, 0x67, 0x86, 0x8d, 0x60, 0x84, 0x2e, 0x40,
	0xf7, 0x19, 0xc3, 0x0d, 0x05, 0xe4, 0x2b, 0xea, 0x41, 0x7b, 0xce, 0x49, 0x91, 0x47, 0x2b, 0x82,
	0x75, 0x85, 0xb7, 0x19, 0xb9, 0x60, 0xbd, 0x45, 0x9c, 0xff, 0xd0, 0x22, 0x79, 0x8e, 0xf8, 0x27,
	0x3e, 0x55, 0xfe, 0x80, 0xa1, 0x3e, 0x98, 0x93, 0xb4, 0xe0, 0xe2, 0x45, 0x16, 0x18, 0xea, 0xc0,
	0x0e, 0xc8, 0xf6, 0x69, 0x54, 0xcb, 0x66, 0xd5, 0xbe, 0xc9, 0xe8, 0x0a, 0x60, 0xfc, 0x2b, 0xe4,
	0x55, 0x59, 0x30, 0xc2, 0x2d, 0x65, 0xf7, 0x08, 0x72, 0xa0, 0x13, 0xf0, 0x29, 0x8d, 0x97, 0x24,
	0x79, 0x5d, 0x0b, 0xdc, 0x76, 0x34, 0xaf, 0x1d, 0xee, 0x23, 0x74, 0x0f, 0xdd, 0x49, 0x94, 0x66,
	0x24, 0xd9, 0x4c, 0xe4, 0x0b, 0x41, 0x56, 0x4c, 0x60, 0xd3, 0xd1, 0x3c, 0x23, 0x3c, 0x2e, 0xd1,
	0x25, 0x18, 0x21, 0xcd, 0x08, 0xc7, 0xe0, 0xe8, 0x9e, 0x19, 0x56, 0x41, 0xde, 0x26, 0x27, 0x9b,
	0xd2, 0x45, 0x9a, 0xfb, 0x02, 0x77, 0x54, 0xc3, 0x3e, 0x92, 0x5f, 0xfa, 0x54, 0x90, 0x48, 0x90,
	0xc4, 0x17, 0xd8, 0x52, 0x7e, 0x07, 0xa4, 0x9d, 0xb3, 0xa4, 0xb6, 0x67, 0x95, 0xdd, 0x02, 0xf7,
	0x06, 0xba, 0xf5, 0x4a, 0x1e, 0xcb, 0x77, 0xba, 0x24, 0x79, 0x48, 0xbe, 0xd6, 0x84, 0xab, 0x61,
	0x54, 0xae, 0x77, 0x54, 0x05, 0xd7, 0x06, 0x6b, 0xbc, 0x62, 0xa2, 0xac, 0x4f, 0xb9, 0x16, 0x40,
	0x9d, 0x59, 0x56, 0xde, 0xce, 0xe0, 0x3c, 0xa8, 0x37, 0x3f, 0x23, 0xc5, 0x77, 0x1a, 0x13, 0xf4,
	0x00, 0xf6, 0x61, 0x3f, 0xea, 0x57, 0x3f, 0xc5, 0xe0, 0xe8, 0xb5, 0x3d, 0xfb, 0xd0, 0xba, 0x27,
	0x1f, 0x4d, 0x05, 0xee, 0xfe, 0x03, 0x00, 0x00, 0xff, 0xff, 0xa9, 0x58, 0xdd, 0x2b, 0x68, 0x02,
	0x00, 0x00,
}
