// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/proto/identity.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Account struct {
	ID                    int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UUID                  string   `protobuf:"bytes,2,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Namespace             string   `protobuf:"bytes,3,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
	Username              string   `protobuf:"bytes,4,opt,name=Username,proto3" json:"Username,omitempty"`
	PasswordHash          string   `protobuf:"bytes,5,opt,name=PasswordHash,proto3" json:"PasswordHash,omitempty"`
	FirstName             string   `protobuf:"bytes,6,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName              string   `protobuf:"bytes,7,opt,name=LastName,proto3" json:"LastName,omitempty"`
	Avatar                string   `protobuf:"bytes,8,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	Email                 string   `protobuf:"bytes,9,opt,name=Email,proto3" json:"Email,omitempty"`
	Mobile                string   `protobuf:"bytes,10,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	ExternalID            string   `protobuf:"bytes,11,opt,name=ExternalID,proto3" json:"ExternalID,omitempty"`
	IsLockedOut           bool     `protobuf:"varint,12,opt,name=IsLockedOut,proto3" json:"IsLockedOut,omitempty"`
	FailedPasswordAttempt int32    `protobuf:"varint,13,opt,name=FailedPasswordAttempt,proto3" json:"FailedPasswordAttempt,omitempty"`
	Roles                 []string `protobuf:"bytes,14,rep,name=Roles,proto3" json:"Roles,omitempty"`
	ClientIP              string   `protobuf:"bytes,15,opt,name=ClientIP,proto3" json:"ClientIP,omitempty"`
	UserAgent             string   `protobuf:"bytes,16,opt,name=UserAgent,proto3" json:"UserAgent,omitempty"`
	Notes                 string   `protobuf:"bytes,17,opt,name=Notes,proto3" json:"Notes,omitempty"`
	LastLoginAt           int32    `protobuf:"varint,18,opt,name=LastLoginAt,proto3" json:"LastLoginAt,omitempty"`
	CreatorID             int64    `protobuf:"varint,19,opt,name=CreatorID,proto3" json:"CreatorID,omitempty"`
	CreatorName           string   `protobuf:"bytes,20,opt,name=CreatorName,proto3" json:"CreatorName,omitempty"`
	CreatedAt             int32    `protobuf:"varint,21,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdaterID             int64    `protobuf:"varint,22,opt,name=UpdaterID,proto3" json:"UpdaterID,omitempty"`
	UpdaterName           string   `protobuf:"bytes,23,opt,name=UpdaterName,proto3" json:"UpdaterName,omitempty"`
	UpdatedAt             int32    `protobuf:"varint,24,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a5bfa4317111365, []int{0}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Account) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *Account) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *Account) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Account) GetPasswordHash() string {
	if m != nil {
		return m.PasswordHash
	}
	return ""
}

func (m *Account) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Account) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Account) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *Account) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Account) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *Account) GetExternalID() string {
	if m != nil {
		return m.ExternalID
	}
	return ""
}

func (m *Account) GetIsLockedOut() bool {
	if m != nil {
		return m.IsLockedOut
	}
	return false
}

func (m *Account) GetFailedPasswordAttempt() int32 {
	if m != nil {
		return m.FailedPasswordAttempt
	}
	return 0
}

func (m *Account) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *Account) GetClientIP() string {
	if m != nil {
		return m.ClientIP
	}
	return ""
}

func (m *Account) GetUserAgent() string {
	if m != nil {
		return m.UserAgent
	}
	return ""
}

func (m *Account) GetNotes() string {
	if m != nil {
		return m.Notes
	}
	return ""
}

func (m *Account) GetLastLoginAt() int32 {
	if m != nil {
		return m.LastLoginAt
	}
	return 0
}

func (m *Account) GetCreatorID() int64 {
	if m != nil {
		return m.CreatorID
	}
	return 0
}

func (m *Account) GetCreatorName() string {
	if m != nil {
		return m.CreatorName
	}
	return ""
}

func (m *Account) GetCreatedAt() int32 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Account) GetUpdaterID() int64 {
	if m != nil {
		return m.UpdaterID
	}
	return 0
}

func (m *Account) GetUpdaterName() string {
	if m != nil {
		return m.UpdaterName
	}
	return ""
}

func (m *Account) GetUpdatedAt() int32 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type AccountByTokenRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountByTokenRequest) Reset()         { *m = AccountByTokenRequest{} }
func (m *AccountByTokenRequest) String() string { return proto.CompactTextString(m) }
func (*AccountByTokenRequest) ProtoMessage()    {}
func (*AccountByTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a5bfa4317111365, []int{1}
}

func (m *AccountByTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountByTokenRequest.Unmarshal(m, b)
}
func (m *AccountByTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountByTokenRequest.Marshal(b, m, deterministic)
}
func (m *AccountByTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountByTokenRequest.Merge(m, src)
}
func (m *AccountByTokenRequest) XXX_Size() int {
	return xxx_messageInfo_AccountByTokenRequest.Size(m)
}
func (m *AccountByTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountByTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountByTokenRequest proto.InternalMessageInfo

func (m *AccountByTokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type EmptyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyRequest) Reset()         { *m = EmptyRequest{} }
func (m *EmptyRequest) String() string { return proto.CompactTextString(m) }
func (*EmptyRequest) ProtoMessage()    {}
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a5bfa4317111365, []int{2}
}

func (m *EmptyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyRequest.Unmarshal(m, b)
}
func (m *EmptyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyRequest.Marshal(b, m, deterministic)
}
func (m *EmptyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyRequest.Merge(m, src)
}
func (m *EmptyRequest) XXX_Size() int {
	return xxx_messageInfo_EmptyRequest.Size(m)
}
func (m *EmptyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyRequest proto.InternalMessageInfo

type EmptyReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyReply) Reset()         { *m = EmptyReply{} }
func (m *EmptyReply) String() string { return proto.CompactTextString(m) }
func (*EmptyReply) ProtoMessage()    {}
func (*EmptyReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a5bfa4317111365, []int{3}
}

func (m *EmptyReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyReply.Unmarshal(m, b)
}
func (m *EmptyReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyReply.Marshal(b, m, deterministic)
}
func (m *EmptyReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyReply.Merge(m, src)
}
func (m *EmptyReply) XXX_Size() int {
	return xxx_messageInfo_EmptyReply.Size(m)
}
func (m *EmptyReply) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyReply.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyReply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Account)(nil), "proto.Account")
	proto.RegisterType((*AccountByTokenRequest)(nil), "proto.AccountByTokenRequest")
	proto.RegisterType((*EmptyRequest)(nil), "proto.EmptyRequest")
	proto.RegisterType((*EmptyReply)(nil), "proto.EmptyReply")
}

func init() { proto.RegisterFile("pkg/proto/identity.proto", fileDescriptor_5a5bfa4317111365) }

var fileDescriptor_5a5bfa4317111365 = []byte{
	// 479 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0x6f, 0x6f, 0xd3, 0x30,
	0x10, 0x87, 0x69, 0xbb, 0x76, 0xed, 0xad, 0xeb, 0xc0, 0xac, 0xe3, 0x34, 0x21, 0x14, 0xe5, 0x55,
	0xdf, 0xb0, 0x89, 0x3f, 0x5f, 0x20, 0x2c, 0x9d, 0x88, 0x54, 0xc6, 0x14, 0xe8, 0x07, 0xf0, 0x9a,
	0x53, 0x89, 0x9a, 0xc4, 0x21, 0x76, 0x07, 0xfd, 0x84, 0x7c, 0x2d, 0xe4, 0x73, 0x9a, 0x06, 0xb4,
	0x57, 0xed, 0xf3, 0x3b, 0xfb, 0xd1, 0xf9, 0x62, 0x03, 0x96, 0x9b, 0xf5, 0x75, 0x59, 0x29, 0xa3,
	0xae, 0xd3, 0x84, 0x0a, 0x93, 0x9a, 0xdd, 0x15, 0xa3, 0xe8, 0xf3, 0x8f, 0xff, 0xa7, 0x0f, 0xc7,
	0xc1, 0x6a, 0xa5, 0xb6, 0x85, 0x11, 0x13, 0xe8, 0x46, 0x21, 0x76, 0xbc, 0xce, 0xac, 0x17, 0x77,
	0xa3, 0x50, 0x08, 0x38, 0x5a, 0x2e, 0xa3, 0x10, 0xbb, 0x5e, 0x67, 0x36, 0x8a, 0xf9, 0xbf, 0x78,
	0x0d, 0xa3, 0x3b, 0x99, 0x93, 0x2e, 0xe5, 0x8a, 0xb0, 0xc7, 0x85, 0x43, 0x20, 0x2e, 0x61, 0xb8,
	0xd4, 0x54, 0x15, 0x32, 0x27, 0x3c, 0xe2, 0x62, 0xc3, 0xc2, 0x87, 0xf1, 0xbd, 0xd4, 0xfa, 0x97,
	0xaa, 0x92, 0xcf, 0x52, 0xff, 0xc0, 0x3e, 0xd7, 0xff, 0xc9, 0xac, 0xfd, 0x36, 0xad, 0xb4, 0xb1,
	0x46, 0x1c, 0x38, 0x7b, 0x13, 0x58, 0xfb, 0x42, 0xd6, 0xc5, 0x63, 0x67, 0xdf, 0xb3, 0xb8, 0x80,
	0x41, 0xf0, 0x28, 0x8d, 0xac, 0x70, 0xc8, 0x95, 0x9a, 0xc4, 0x39, 0xf4, 0xe7, 0xb9, 0x4c, 0x33,
	0x1c, 0x71, 0xec, 0xc0, 0xae, 0xfe, 0xa2, 0x1e, 0xd2, 0x8c, 0x10, 0xdc, 0x6a, 0x47, 0xe2, 0x0d,
	0xc0, 0xfc, 0xb7, 0xb1, 0x0d, 0x67, 0x51, 0x88, 0x27, 0x5c, 0x6b, 0x25, 0xc2, 0x83, 0x93, 0x48,
	0x2f, 0xd4, 0x6a, 0x43, 0xc9, 0xd7, 0xad, 0xc1, 0xb1, 0xd7, 0x99, 0x0d, 0xe3, 0x76, 0x24, 0x3e,
	0xc2, 0xf4, 0x56, 0xa6, 0x19, 0x25, 0xfb, 0x73, 0x05, 0xc6, 0x50, 0x5e, 0x1a, 0x3c, 0xf5, 0x3a,
	0xb3, 0x7e, 0xfc, 0x74, 0xd1, 0x76, 0x19, 0xab, 0x8c, 0x34, 0x4e, 0xbc, 0x9e, 0xed, 0x92, 0xc1,
	0x9e, 0xf7, 0x26, 0x4b, 0xa9, 0x30, 0xd1, 0x3d, 0x9e, 0xb9, 0xf3, 0xee, 0xd9, 0x4e, 0xca, 0x4e,
	0x36, 0x58, 0x53, 0x61, 0xf0, 0xb9, 0x9b, 0x54, 0x13, 0x58, 0xdf, 0x9d, 0x32, 0xa4, 0xf1, 0x85,
	0x3b, 0x35, 0x83, 0xed, 0xde, 0xce, 0x6b, 0xa1, 0xd6, 0x69, 0x11, 0x18, 0x14, 0xdc, 0x51, 0x3b,
	0xb2, 0xd6, 0x9b, 0x8a, 0xa4, 0x51, 0x55, 0x14, 0xe2, 0x4b, 0xbe, 0x08, 0x87, 0xc0, 0xee, 0xaf,
	0x81, 0x3f, 0xc1, 0x39, 0xbb, 0xdb, 0x51, 0xb3, 0x9f, 0x92, 0xc0, 0xe0, 0x94, 0xfd, 0x87, 0x80,
	0x7b, 0x2e, 0x13, 0x69, 0xc8, 0xda, 0x2f, 0x9c, 0xbd, 0x09, 0xac, 0xbd, 0x06, 0xb6, 0xbf, 0x72,
	0xf6, 0x56, 0x74, 0xd8, 0x6f, 0xed, 0xe8, 0xec, 0x4d, 0xe0, 0xbf, 0x85, 0x69, 0x7d, 0x91, 0x3f,
	0xed, 0xbe, 0xab, 0x0d, 0x15, 0x31, 0xfd, 0xdc, 0x92, 0xe6, 0x61, 0x30, 0xf3, 0xcd, 0x1e, 0xc5,
	0x0e, 0xfc, 0x09, 0x8c, 0xe7, 0x79, 0x69, 0x76, 0xf5, 0x2a, 0x7f, 0x0c, 0x50, 0x73, 0x99, 0xed,
	0xde, 0x87, 0x70, 0x16, 0xd5, 0xef, 0xe5, 0x1b, 0x55, 0x8f, 0xe9, 0x8a, 0xc4, 0x3b, 0x38, 0x75,
	0x47, 0x69, 0x9e, 0x8b, 0x7b, 0x49, 0x57, 0x35, 0x5f, 0xfe, 0xc7, 0xfe, 0xb3, 0x87, 0x01, 0x07,
	0x1f, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0xac, 0x95, 0xb2, 0x09, 0x86, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// IdentityServiceClient is the client API for IdentityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IdentityServiceClient interface {
	CreateAccount(ctx context.Context, in *Account, opts ...grpc.CallOption) (*Account, error)
}

type identityServiceClient struct {
	cc *grpc.ClientConn
}

func NewIdentityServiceClient(cc *grpc.ClientConn) IdentityServiceClient {
	return &identityServiceClient{cc}
}

func (c *identityServiceClient) CreateAccount(ctx context.Context, in *Account, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := c.cc.Invoke(ctx, "/proto.IdentityService/CreateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityServiceServer is the server API for IdentityService service.
type IdentityServiceServer interface {
	CreateAccount(context.Context, *Account) (*Account, error)
}

// UnimplementedIdentityServiceServer can be embedded to have forward compatible implementations.
type UnimplementedIdentityServiceServer struct {
}

func (*UnimplementedIdentityServiceServer) CreateAccount(ctx context.Context, req *Account) (*Account, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAccount not implemented")
}

func RegisterIdentityServiceServer(s *grpc.Server, srv IdentityServiceServer) {
	s.RegisterService(&_IdentityService_serviceDesc, srv)
}

func _IdentityService_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Account)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.IdentityService/CreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).CreateAccount(ctx, req.(*Account))
	}
	return interceptor(ctx, in, info, handler)
}

var _IdentityService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.IdentityService",
	HandlerType: (*IdentityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccount",
			Handler:    _IdentityService_CreateAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/identity.proto",
}
